add_newline = false

format = "$conda$directory$git_branch$git_status$character"

[directory]
truncation_length = -1
truncate_to_repo = false
style = "bold #38BDF8"

[git_branch]
# symbol = "git:"
style = "bold #FB8500"

[git_status]
style = "bold #38BDF8"

# [python]
# format = " [py:$virtualenv]($style)"
# detect_extensions = []
# detect_folders = []

[character]
success_symbol = "[√](bold #00a600)"
error_symbol = "[×](bold #c00000)"

[conda]
format = '[\($environment\)](bold #FB8500) '
ignore_base = false
